CREATE TABLE administradores(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	senha VARCHAR(20) NOT NULL
)

CREATE TABLE categorias(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE compras(
	id SERIAL PRIMARY KEY,
	numero INTEGER NOT NULL
	produto VARCHAR(50) NOT NULL,
	cliente VARCHAR(50) NOT NULL,
	valor REAL NOT NULL,
	data TIMESTAMP NOT NULL
	
)

CREATE TABLE produtos(
	id SERIAL PRIMARY KEY,
	categoria VARCHAR(50) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	descricao VARCHAR(255) NOT NULL,
	preco REAL NOT NULL    
)

CREATE TABLE clientes(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	senha VARCHAR(50) NOT NULL,
	cartao VARCHAR(50) NOT NULL,
	cpf VARCHAR(11) NOT NULL
)

CREATE TABLE clientes(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	senha VARCHAR(50) NOT NULL
)